[pytest]
pythonpath = .

markers =
    unit: Быстрые тесты без внешних зависимостей (моки)
    integration: Тесты, требующие реальных внешних систем
    e2e: Полные End-to-End тесты (медленные)

asyncio_mode = strict

testpaths = tests

addopts = -v --tb=short
