# Образ для разработки (development)
FROM python:3.12-slim AS dev

WORKDIR app/

COPY ./requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

# Образ для Kubernetes (production)
FROM python:3.12-slim AS prod

WORKDIR /app

COPY init_dwh/. ./
COPY dwh/ ./dwh/
COPY config/crypto/ ./crypto/

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "main.py"]
