FROM apache/airflow:2.11.0-python3.11

RUN pip install --upgrade pip && \
    pip install --upgrade \
        apache-airflow-providers-cncf-kubernetes==10.16.1 \
        cryptography==44.0.3 \
        pyOpenSSL==25.1.0 \
        boto3==1.37.3 \
        apache-airflow-providers-amazon
