FROM apache/airflow:2.11.0-python3.11

RUN pip install --no-cache-dir \
    apache-airflow-providers-cncf-kubernetes==10.16.1
#     minio==7.2.20 \
#     clickhouse-connect==0.14.1 \
#     kafka-python==2.3.0 \
#     pyarrow==23.0.1 \
#     apache-airflow-providers-apache-iceberg==2.0.1
#     pyiceberg==0.11.1

    #ccxt==4.5.51 \
    #massive==2.0.2 